apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-deployment
  labels:
    app: employees-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: employees-app
    template:
      matadata:
        labels:
          app: employees-app
        spec:
          containers:
          - name: mysql
            image: mysql:latest
            resources:
              requests:
                memory: "256Mi"
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: g1we438837efd
            - name: MYSQL_DATABASE
              value: employeesuser
            - name: MYSQL_PASSWORD
              value: g1we438837efd
            ports:
            - containerPort: 3306
          - name: employees
            image: nginx:latest
            resources:
              requests:
                memory: "256Mi"
                cpu: "1"
            env:
            - name: EMPLOYEE_JAPAN_SERVICE
              value: employees-japan-service
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PASSWORD
              value: g1we438837efd
            - name: nginx-employees
              image: nginx:latest
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "25m"
                limits:
                  memory: "256Mi"
                  cpu: "1"
              ports:
              - containerPort: 80

